apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: flask
  namespace: test-namespace
spec:
  interval: 5m
  chart:
    spec:
      chart: ./chart
      version: "4"
      sourceRef:
        kind: GitRepository
        name: gitops-series 
        namespace: flux-system
      interval: 1m 
  values:
    name: flask
    ingress_enabled: false
