apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: flask
  namespace: test-namespace
spec:
  releaseName: flask
  chart:
    git: https://github.com/paktek123/gitops-series
    ref: main
    path: chart
  values:
    name: flask
