apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: flask
  namespace: test-namespace
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: flask
          servicePort: 5000
