apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/
  - ./flask-different-cluster/
patchesStrategicMerge:
  - patches/ingress-nginx-deployment.yaml
  - patches/ingress-nginx-service.yaml
