apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    test: label
spec:
  selector:
    app: {{ .Values.name }}
  ports:
    - protocol: TCP
      port: 5000
