apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: flask
  namespace: test-namespace
spec:
  interval: 5m
  chart:
    spec:
      chart: "flask-application"
      version: "2"
      sourceRef:
        kind: HelmRepository
        name: localchartmuseum
        namespace: flux-system
      interval: 1m
  values:
    name: flask
