apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: flask-internal
  namespace: test-namespace
spec:
  releaseName: flask-internal
  chart:
    git: https://github.com/paktek123/gitops-series
    ref: main
    path: chart
  values:
    name: flask-internal
    application_name: internal
    application_cluster: development
