apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: flask-different-namespace
  namespace: service2
spec:
  releaseName: flask-different-namespace
  chart:
    git: https://github.com/paktek123/gitops-series
    ref: main
    path: chart
  values:
    name: flask-different-namespace
    namespace: service2
    application_name: service2
    application_cluster: development
