apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: flask-different-namespace
  namespace: service2
spec:
  interval: 5m
  releaseName: flask-different-namespace
  chart:
    spec:
      chart: "./chart"
      version: "3"
      sourceRef:
        kind: GitRepository
        name: gitops-series
        namespace: flux-system
      interval: 1m
  values:
    name: flask-different-namespace
    namespace: service2
    application_name: service2
    application_cluster: development
    ingress_enabled: false
